name: 🚀 First-Time Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧠 Set REPO_URL environment
        run: echo "REPO_URL=git@github.com:${{ github.repository }}.git" >> $GITHUB_ENV

      - name: 🔐 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: REPO_URL
          script: |
            export APP_PORT=8000
            export PORT=8000
            export REDIS_PORT=6379
            export REDIS_HOST=redis
            export DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN}}

            # Define project dir
            PROJECT_DIR=Pirateman

            echo "📦 Cloning from $REPO_URL"

            # If project doesn't exist, clone it
            if [ ! -d "$PROJECT_DIR" ]; then
              git clone $REPO_URL $PROJECT_DIR
            fi

            # Go into project, pull latest, and deploy
            cd $PROJECT_DIR
            git pull origin main
            docker-compose pull
            docker-compose up -d --build --remove-orphans

            echo "✅ First-time deployment done"
