name: 🚀 First-Time Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 💡 Set repo URL
        run: echo "REPO_URL=git@github.com:${{ github.repository }}.git" >> repo.env

      - name: 🔐 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: REPO_URL
          script: |
            # Define project dir
            PROJECT_DIR=Pirateman

            echo "📦 Cloning from $REPO_URL"

            # If project doesn't exist, clone it
            if [ ! -d "$PROJECT_DIR" ]; then
              git clone $REPO_URL $PROJECT_DIR
            fi

            # Go into project, pull latest, and deploy
            cd $PROJECT_DIR
            git pull origin main
            docker-compose pull
            docker-compose up -d --build

            echo "✅ First-time deployment done"
